name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Navigate to app directory or clone if it doesn't exist
            if [ -d "Deploying-a-Node.js-App-with-GitHub-Actions-and-Docker-on-AWS-EC2" ]; then
              cd Deploying-a-Node.js-App-with-GitHub-Actions-and-Docker-on-AWS-EC2
              git pull origin main
            else
              git clone https://github.com/swakall/Deploying-a-Node.js-App-with-GitHub-Actions-and-Docker-on-AWS-EC2.git
              cd Deploying-a-Node.js-App-with-GitHub-Actions-and-Docker-on-AWS-EC2
            fi

            # Stop and remove existing container if running
            docker stop my-node-app || true
            docker rm my-node-app || true

            # Build and run the Docker container
            docker build -t my-node-app .
            docker run -d -p 3000:3000 --name my-node-app my-node-app
          EOF
